-- MySQL Script generated by MySQL Workbench
-- 03/25/15 13:10:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UF` (
  `idUF` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  PRIMARY KEY (`idUF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `idMunicipio` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `UF_idUF` INT NOT NULL,
  `UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`, `UF_idUF`, `UF_idUF1`),
  INDEX `fk_Municipio_UF1_idx` (`UF_idUF1` ASC),
  CONSTRAINT `fk_Municipio_UF1`
    FOREIGN KEY (`UF_idUF1`)
    REFERENCES `mydb`.`UF` (`idUF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bairro` (
  `idBairro` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `Municipio_idMunicipio` INT NOT NULL,
  `Municipio_UF_idUF` INT NOT NULL,
  `Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idBairro`, `Municipio_idMunicipio`, `Municipio_UF_idUF`, `Municipio_UF_idUF1`),
  INDEX `fk_Bairro_Municipio1_idx` (`Municipio_idMunicipio` ASC, `Municipio_UF_idUF` ASC, `Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Bairro_Municipio1`
    FOREIGN KEY (`Municipio_idMunicipio` , `Municipio_UF_idUF` , `Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Municipio` (`idMunicipio` , `UF_idUF` , `UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Logradouro` (
  `idLogradouro` INT NOT NULL,
  `nome` VARCHAR(1000) NULL,
  `CEP` VARCHAR(100) NULL,
  `Bairro_idBairro` INT NOT NULL,
  `Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idLogradouro`, `Bairro_idBairro`, `Bairro_Municipio_idMunicipio`, `Bairro_Municipio_UF_idUF`, `Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Logradouro_Bairro1_idx` (`Bairro_idBairro` ASC, `Bairro_Municipio_idMunicipio` ASC, `Bairro_Municipio_UF_idUF` ASC, `Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Logradouro_Bairro1`
    FOREIGN KEY (`Bairro_idBairro` , `Bairro_Municipio_idMunicipio` , `Bairro_Municipio_UF_idUF` , `Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Bairro` (`idBairro` , `Municipio_idMunicipio` , `Municipio_UF_idUF` , `Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `perfil` VARCHAR(100) NULL,
  `sexo` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `foto` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `RG` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL,
  `dataIngresso` DATE NULL,
  `dataSaida` DATE NULL,
  `Logradouro_idLogradouro` INT NOT NULL,
  `Logradouro_Bairro_idBairro` INT NOT NULL,
  `Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(1000) NULL,
  PRIMARY KEY (`idUsuario`, `Logradouro_idLogradouro`, `Logradouro_Bairro_idBairro`, `Logradouro_Bairro_Municipio_idMunicipio`, `Logradouro_Bairro_Municipio_UF_idUF`, `Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Usuario_Logradouro1_idx` (`Logradouro_idLogradouro` ASC, `Logradouro_Bairro_idBairro` ASC, `Logradouro_Bairro_Municipio_idMunicipio` ASC, `Logradouro_Bairro_Municipio_UF_idUF` ASC, `Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Usuario_Logradouro1`
    FOREIGN KEY (`Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Logradouro` (`idLogradouro` , `Bairro_idBairro` , `Bairro_Municipio_idMunicipio` , `Bairro_Municipio_UF_idUF` , `Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `Adimplente` TINYINT(1) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idResponsavel`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Responsavel_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Responsavel_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `idAluno` INT NOT NULL,
  `escolaAnterior` VARCHAR(100) NULL,
  `serieAnterior` VARCHAR(100) NULL,
  `escolaAtual` VARCHAR(100) NULL,
  `serieAtual` VARCHAR(100) NULL,
  `Responsavel_idResponsavel` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `Responsavel_idResponsavel`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Aluno_Responsavel1_idx` (`Responsavel_idResponsavel` ASC),
  INDEX `fk_Aluno_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Aluno_Responsavel1`
    FOREIGN KEY (`Responsavel_idResponsavel`)
    REFERENCES `mydb`.`Responsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serie` (
  `idSerie` INT NOT NULL,
  `periodo` VARCHAR(45) NULL,
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Periodo` (
  `idPeriodo` INT NOT NULL,
  `periodo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `idTurma` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `qtdAlunosLimite` VARCHAR(45) NULL,
  `qtdAlunosInseridos` VARCHAR(45) NULL,
  `ano` YEAR NULL,
  `Serie_idSerie` INT NOT NULL,
  `Periodo_idPeriodo` INT NOT NULL,
  PRIMARY KEY (`idTurma`, `Serie_idSerie`, `Periodo_idPeriodo`),
  INDEX `fk_Turma_Serie1_idx` (`Serie_idSerie` ASC),
  INDEX `fk_Turma_Periodo1_idx` (`Periodo_idPeriodo` ASC),
  CONSTRAINT `fk_Turma_Serie1`
    FOREIGN KEY (`Serie_idSerie`)
    REFERENCES `mydb`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_Periodo1`
    FOREIGN KEY (`Periodo_idPeriodo`)
    REFERENCES `mydb`.`Periodo` (`idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matricula_Aluno_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matricula_Aluno_Turma` (
  `Turma_idTurma` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Aluno_idAluno`),
  INDEX `fk_Turma_has_Aluno_Aluno1_idx` (`Aluno_idAluno` ASC),
  INDEX `fk_Turma_has_Aluno_Turma_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Turma_has_Aluno_Turma`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL,
  `escolaAnterior` VARCHAR(500) NULL,
  `formacaoAcademica` VARCHAR(500) NULL,
  `instituicaoAcademica` VARCHAR(500) NULL,
  `anoConclusao` DATE NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Professor_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `nomeDisciplina` VARCHAR(45) NULL,
  `conteudoDisciplina` VARCHAR(1000) NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gera_boletim_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gera_boletim_turma` (
  `Boletim_idBoletim` INT(11) NOT NULL,
  `Turma_idTurma` INT(11) NOT NULL,
  PRIMARY KEY (`Boletim_idBoletim`, `Turma_idTurma`),
  INDEX `fk_Boletim_has_Turma_Turma1_idx` (`Turma_idTurma` ASC),
  INDEX `fk_Boletim_has_Turma_Boletim1_idx` (`Boletim_idBoletim` ASC),
  CONSTRAINT `fk_Boletim_has_Turma_Boletim1`
    FOREIGN KEY (`Boletim_idBoletim`)
    REFERENCES `gaeddb`.`boletim` (`idBoletim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boletim_has_Turma_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `gaeddb`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`ministra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ministra` (
  `Professor_idProfessor` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Disciplina_idDisciplina`),
  INDEX `fk_Professor_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  INDEX `fk_Professor_has_Disciplina_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Professor_has_Disciplina_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`leciona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`leciona` (
  `Turma_idTurma` INT(11) NOT NULL,
  `Professor_has_Disciplina_Professor_idProfessor` INT(11) NOT NULL,
  `Professor_has_Disciplina_Disciplina_idDisciplina` INT(11) NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Professor_has_Disciplina_Professor_idProfessor`, `Professor_has_Disciplina_Disciplina_idDisciplina`),
  INDEX `fk_Turma_has_Professor_has_Disciplina_Professor_has_Discipl_idx` (`Professor_has_Disciplina_Professor_idProfessor` ASC, `Professor_has_Disciplina_Disciplina_idDisciplina` ASC),
  INDEX `fk_Turma_has_Professor_has_Disciplina_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Turma_has_Professor_has_Disciplina_Professor_has_Disciplina1`
    FOREIGN KEY (`Professor_has_Disciplina_Professor_idProfessor` , `Professor_has_Disciplina_Disciplina_idDisciplina`)
    REFERENCES `mydb`.`ministra` (`Professor_idProfessor` , `Disciplina_idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Professor_has_Disciplina_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `gaeddb`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`matricula_aluno_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matricula_aluno_turma` (
  `Turma_idTurma` INT(11) NOT NULL,
  `Aluno_idAluno` INT(11) NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Aluno_idAluno`),
  INDEX `fk_Turma_has_Aluno_Aluno1_idx` (`Aluno_idAluno` ASC),
  INDEX `fk_Turma_has_Aluno_Turma_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Turma_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `gaeddb`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Aluno_Turma`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `gaeddb`.`turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`ministra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ministra` (
  `Professor_idProfessor` INT NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Disciplina_idDisciplina`),
  INDEX `fk_Professor_has_Disciplina_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  INDEX `fk_Professor_has_Disciplina_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Professor_has_Disciplina_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Disciplina_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Leciona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Leciona` (
  `Turma_idTurma` INT NOT NULL,
  `Professor_has_Disciplina_Professor_idProfessor` INT NOT NULL,
  `Professor_has_Disciplina_Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Professor_has_Disciplina_Professor_idProfessor`, `Professor_has_Disciplina_Disciplina_idDisciplina`),
  INDEX `fk_Turma_has_Professor_has_Disciplina_Professor_has_Discipl_idx` (`Professor_has_Disciplina_Professor_idProfessor` ASC, `Professor_has_Disciplina_Disciplina_idDisciplina` ASC),
  INDEX `fk_Turma_has_Professor_has_Disciplina_Turma1_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Turma_has_Professor_has_Disciplina_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Professor_has_Disciplina_Professor_has_Disciplina1`
    FOREIGN KEY (`Professor_has_Disciplina_Professor_idProfessor` , `Professor_has_Disciplina_Disciplina_idDisciplina`)
    REFERENCES `mydb`.`ministra` (`Professor_idProfessor` , `Disciplina_idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bimestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bimestre` (
  `idBimestre` INT NOT NULL,
  `nomeBimestre` VARCHAR(45) NULL,
  `datainicio` DATE NULL,
  `datafinal` DATE NULL,
  PRIMARY KEY (`idBimestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boletim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boletim` (
  `idBoletim` INT NOT NULL,
  `Bimestre_idBimestre` INT NOT NULL,
  PRIMARY KEY (`idBoletim`),
  INDEX `fk_Boletim_Bimestre1_idx` (`Bimestre_idBimestre` ASC),
  CONSTRAINT `fk_Boletim_Bimestre1`
    FOREIGN KEY (`Bimestre_idBimestre`)
    REFERENCES `mydb`.`Bimestre` (`idBimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gera_Boletim_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gera_Boletim_Turma` (
  `Boletim_idBoletim` INT NOT NULL,
  `Turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`Boletim_idBoletim`, `Turma_idTurma`),
  INDEX `fk_Boletim_has_Turma_Turma1_idx` (`Turma_idTurma` ASC),
  INDEX `fk_Boletim_has_Turma_Boletim1_idx` (`Boletim_idBoletim` ASC),
  CONSTRAINT `fk_Boletim_has_Turma_Boletim1`
    FOREIGN KEY (`Boletim_idBoletim`)
    REFERENCES `mydb`.`Boletim` (`idBoletim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boletim_has_Turma_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `mydb`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boletim_has_Ministra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boletim_has_Ministra` (
  `Ministra_Professor_idProfessor` INT NOT NULL,
  `Ministra_Disciplina_idDisciplina` INT NOT NULL,
  `nota` FLOAT NULL,
  `faltas` INT NULL,
  `Boletim_idBoletim` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Aluno_Responsavel_idResponsavel` INT NOT NULL,
  `Aluno_Usuario_idUsuario` INT NOT NULL,
  `Aluno_Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`Ministra_Professor_idProfessor`, `Ministra_Disciplina_idDisciplina`, `Aluno_idAluno`, `Aluno_Responsavel_idResponsavel`, `Aluno_Usuario_idUsuario`, `Aluno_Usuario_Logradouro_idLogradouro`, `Aluno_Usuario_Logradouro_Bairro_idBairro`, `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Boletim_has_Ministra_Ministra1_idx` (`Ministra_Professor_idProfessor` ASC, `Ministra_Disciplina_idDisciplina` ASC),
  INDEX `fk_Boletim_has_Ministra_Boletim1_idx` (`Boletim_idBoletim` ASC),
  INDEX `fk_Boletim_has_Ministra_Aluno1_idx` (`Aluno_idAluno` ASC, `Aluno_Responsavel_idResponsavel` ASC, `Aluno_Usuario_idUsuario` ASC, `Aluno_Usuario_Logradouro_idLogradouro` ASC, `Aluno_Usuario_Logradouro_Bairro_idBairro` ASC, `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Boletim_has_Ministra_Ministra1`
    FOREIGN KEY (`Ministra_Professor_idProfessor` , `Ministra_Disciplina_idDisciplina`)
    REFERENCES `mydb`.`ministra` (`Professor_idProfessor` , `Disciplina_idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boletim_has_Ministra_Boletim1`
    FOREIGN KEY (`Boletim_idBoletim`)
    REFERENCES `mydb`.`Boletim` (`idBoletim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Boletim_has_Ministra_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Responsavel_idResponsavel` , `Aluno_Usuario_idUsuario` , `Aluno_Usuario_Logradouro_idLogradouro` , `Aluno_Usuario_Logradouro_Bairro_idBairro` , `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Responsavel_idResponsavel` , `Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_has_Usuario` (
  `Aluno_idAluno` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Aluno_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  INDEX `fk_Aluno_has_Usuario_Aluno1_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Aluno_has_Usuario_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel_has_Usuario` (
  `Responsavel_idResponsavel` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`Responsavel_idResponsavel`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Responsavel_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  INDEX `fk_Responsavel_has_Usuario_Responsavel1_idx` (`Responsavel_idResponsavel` ASC),
  CONSTRAINT `fk_Responsavel_has_Usuario_Responsavel1`
    FOREIGN KEY (`Responsavel_idResponsavel`)
    REFERENCES `mydb`.`Responsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsavel_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor_has_Usuario` (
  `Professor_idProfessor` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Professor_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  INDEX `fk_Professor_has_Usuario_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Professor_has_Usuario_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `mydb`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Secretaria` (
  `idSecretaria` INT NOT NULL,
  `experienciaAnterior` VARCHAR(1000) NULL,
  `instituicaoAnterior` VARCHAR(1000) NULL,
  `formacaoAcademica` VARCHAR(1000) NULL,
  `instituicaoAcademica` VARCHAR(1000) NULL,
  `anoConclusao` DATE NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idSecretaria`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Secretaria_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Secretaria_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Secretaria_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Secretaria_has_Usuario` (
  `Secretaria_idSecretaria` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`Secretaria_idSecretaria`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Secretaria_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  INDEX `fk_Secretaria_has_Usuario_Secretaria1_idx` (`Secretaria_idSecretaria` ASC),
  CONSTRAINT `fk_Secretaria_has_Usuario_Secretaria1`
    FOREIGN KEY (`Secretaria_idSecretaria`)
    REFERENCES `mydb`.`Secretaria` (`idSecretaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Secretaria_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestor` (
  `idGestor` INT NOT NULL,
  `formacaoAcademica` VARCHAR(1000) NULL,
  `instituicaoAcademica` VARCHAR(1000) NULL,
  `anoConclusao` DATE NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idGestor`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Gestor_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Gestor_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gestor_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gestor_has_Usuario` (
  `Gestor_idGestor` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`Gestor_idGestor`, `Usuario_idUsuario`, `Usuario_Logradouro_idLogradouro`, `Usuario_Logradouro_Bairro_idBairro`, `Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Gestor_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_Logradouro_idLogradouro` ASC, `Usuario_Logradouro_Bairro_idBairro` ASC, `Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  INDEX `fk_Gestor_has_Usuario_Gestor1_idx` (`Gestor_idGestor` ASC),
  CONSTRAINT `fk_Gestor_has_Usuario_Gestor1`
    FOREIGN KEY (`Gestor_idGestor`)
    REFERENCES `mydb`.`Gestor` (`idGestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gestor_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Usuario` (`idUsuario` , `Logradouro_idLogradouro` , `Logradouro_Bairro_idBairro` , `Logradouro_Bairro_Municipio_idMunicipio` , `Logradouro_Bairro_Municipio_UF_idUF` , `Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarefa` (
  `idTarefa` INT NOT NULL,
  `descricaoTarefa` VARCHAR(1000) NULL,
  `prazoTarefa` DATE NULL,
  `statusTarefa` TINYINT(1) NULL,
  `dataTarefa` DATE NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`idTarefa`, `Disciplina_idDisciplina`),
  INDEX `fk_Tarefa_Disciplina1_idx` (`Disciplina_idDisciplina` ASC),
  CONSTRAINT `fk_Tarefa_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`faz_Turma_Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`faz_Turma_Tarefa` (
  `Turma_idTurma` INT NOT NULL,
  `Turma_Serie_idSerie` INT NOT NULL,
  `Turma_Periodo_idPeriodo` INT NOT NULL,
  `Tarefa_idTarefa` INT NOT NULL,
  `Tarefa_Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Turma_idTurma`, `Turma_Serie_idSerie`, `Turma_Periodo_idPeriodo`, `Tarefa_idTarefa`, `Tarefa_Disciplina_idDisciplina`),
  INDEX `fk_Turma_has_Tarefa_Tarefa1_idx` (`Tarefa_idTarefa` ASC, `Tarefa_Disciplina_idDisciplina` ASC),
  INDEX `fk_Turma_has_Tarefa_Turma1_idx` (`Turma_idTurma` ASC, `Turma_Serie_idSerie` ASC, `Turma_Periodo_idPeriodo` ASC),
  CONSTRAINT `fk_Turma_has_Tarefa_Turma1`
    FOREIGN KEY (`Turma_idTurma` , `Turma_Serie_idSerie` , `Turma_Periodo_idPeriodo`)
    REFERENCES `mydb`.`Turma` (`idTurma` , `Serie_idSerie` , `Periodo_idPeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turma_has_Tarefa_Tarefa1`
    FOREIGN KEY (`Tarefa_idTarefa` , `Tarefa_Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Tarefa` (`idTarefa` , `Disciplina_idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`designa_Professor_Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`designa_Professor_Tarefa` (
  `Professor_idProfessor` INT NOT NULL,
  `Professor_Usuario_idUsuario` INT NOT NULL,
  `Professor_Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Professor_Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Professor_Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  `Tarefa_idTarefa` INT NOT NULL,
  `Tarefa_Disciplina_idDisciplina` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Professor_Usuario_idUsuario`, `Professor_Usuario_Logradouro_idLogradouro`, `Professor_Usuario_Logradouro_Bairro_idBairro`, `Professor_Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF1`, `Tarefa_idTarefa`, `Tarefa_Disciplina_idDisciplina`),
  INDEX `fk_Professor_has_Tarefa_Tarefa1_idx` (`Tarefa_idTarefa` ASC, `Tarefa_Disciplina_idDisciplina` ASC),
  INDEX `fk_Professor_has_Tarefa_Professor1_idx` (`Professor_idProfessor` ASC, `Professor_Usuario_idUsuario` ASC, `Professor_Usuario_Logradouro_idLogradouro` ASC, `Professor_Usuario_Logradouro_Bairro_idBairro` ASC, `Professor_Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Professor_has_Tarefa_Professor1`
    FOREIGN KEY (`Professor_idProfessor` , `Professor_Usuario_idUsuario` , `Professor_Usuario_Logradouro_idLogradouro` , `Professor_Usuario_Logradouro_Bairro_idBairro` , `Professor_Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Professor_Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Professor` (`idProfessor` , `Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Tarefa_Tarefa1`
    FOREIGN KEY (`Tarefa_idTarefa` , `Tarefa_Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Tarefa` (`idTarefa` , `Disciplina_idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ocorrencia` (
  `idOcorrencia` INT NOT NULL,
  `assuntoOcorrencia` VARCHAR(200) NULL,
  `dataOcorrencia` DATE NULL,
  `descricaoOcorrencia` VARCHAR(2000) NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Aluno_Responsavel_idResponsavel` INT NOT NULL,
  `Aluno_Usuario_idUsuario` INT NOT NULL,
  `Aluno_Usuario_Logradouro_idLogradouro` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_idBairro` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF` INT NOT NULL,
  `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1` INT NOT NULL,
  PRIMARY KEY (`idOcorrencia`, `Aluno_idAluno`, `Aluno_Responsavel_idResponsavel`, `Aluno_Usuario_idUsuario`, `Aluno_Usuario_Logradouro_idLogradouro`, `Aluno_Usuario_Logradouro_Bairro_idBairro`, `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio`, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF`, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1`),
  INDEX `fk_Ocorrencia_Aluno1_idx` (`Aluno_idAluno` ASC, `Aluno_Responsavel_idResponsavel` ASC, `Aluno_Usuario_idUsuario` ASC, `Aluno_Usuario_Logradouro_idLogradouro` ASC, `Aluno_Usuario_Logradouro_Bairro_idBairro` ASC, `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio` ASC, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF` ASC, `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1` ASC),
  CONSTRAINT `fk_Ocorrencia_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Responsavel_idResponsavel` , `Aluno_Usuario_idUsuario` , `Aluno_Usuario_Logradouro_idLogradouro` , `Aluno_Usuario_Logradouro_Bairro_idBairro` , `Aluno_Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Aluno_Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    REFERENCES `mydb`.`Aluno` (`idAluno` , `Responsavel_idResponsavel` , `Usuario_idUsuario` , `Usuario_Logradouro_idLogradouro` , `Usuario_Logradouro_Bairro_idBairro` , `Usuario_Logradouro_Bairro_Municipio_idMunicipio` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF` , `Usuario_Logradouro_Bairro_Municipio_UF_idUF1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
